Fix DA serial compilation failure introduced in commit dba34646 (#927)
TYPE: bug fix

KEYWORDS: WRFDA, serial, compile

SOURCE: Jamie Bresch (NCAR)

DESCRIPTION OF CHANGES:
The error message of serial build:
```
da_vtox_transforms.f:44:26:
    use da_par_util, only : true_mpi_real, mpi_sum, comm
                           1
Error: Symbol 'true_mpi_real' referenced at (1) not found in module 'da_par_util'
da_vtox_transforms.f:44:41:
    use da_par_util, only : true_mpi_real, mpi_sum, comm
                                          1
Error: Symbol 'mpi_sum' referenced at (1) not found in module 'da_par_util'
```
The fix is to move the line of code
use da_par_util, only : true_mpi_real, mpi_sum, comm
inside #ifdef DM_PARALLEL.

ISSUE:
Fixes #923

LIST OF MODIFIED FILES:
modified:   var/da/da_vtox_transforms/da_vtox_transforms.f90

TESTS CONDUCTED:
WRFDA builds for serial mode after the fix.

RELEASE NOTE: Fix WRFDA V4.1.1 serial compilation failure.